version: 2.0.0.{build}
image: Visual Studio 2017


environment:
  matrix:
    #- PlatformToolset: v140_xp
    - PlatformToolset: v141_xp

platform:
    - Win32
    - x64

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%PlatformToolset%"=="v140_xp" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="v141_xp" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%


build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild NotepadStarter.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%"  /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        $ZipFileName = "NotepadStarter_${env:APPVEYOR_REPO_TAG_NAME}_$env:PLATFORM_INPUT.zip"

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release") {
            cd bin\plugins
            7z a ..\..\$ZipFileName *
            cd ..\..
            Push-AppveyorArtifact $ZipFileName -FileName NotepadStarter.zip
        }

        echo NotepadStarter_${env:APPVEYOR_REPO_TAG_NAME}_$env:PLATFORM_INPUT.zip

        echo "APPVEYOR_REPO_TAG: $env:APPVEYOR_REPO_TAG"

        echo ${env:APPVEYOR_REPO_TAG_NAME}

        echo "$ZipFileName"

        echo ${env:GITHUB_TOKEN}

artifacts:
  - path: NotepadStarter_$(APPVEYOR_REPO_TAG_NAME)_$(PLATFORM_INPUT).zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: cZ6XJJctTlNry5zcr0xygBlDMOxkX5O6pr/C4fNW1qQHLlnVvmuVMajlOFPcMqFl
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v141_xp
        configuration: Release
