version: 2.0.0.{build}
image: Visual Studio 2017


environment:
  matrix:
    - PlatformToolset: v140_xp
    - PlatformToolset: v141_xp

platform:
    - Win32
    - x64

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="Win32" set archi=x86
    - if "%platform%"=="Win32" set platform_input=Win32

    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="x64" set platform_input=x64

    - if "%PlatformToolset%"=="v140_xp" call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%
    - if "%PlatformToolset%"=="v141_xp" call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %archi%


build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - msbuild NotepadStarter.sln /m /p:configuration="%configuration%" /p:platform="%platform_input%"  /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM_INPUT -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\$env:PLATFORM_INPUT\$env:CONFIGURATION\NotepadStarterPlugin.dll" -FileName NotepadStarterPlugin.dll
        }

        if ($env:PLATFORM_INPUT -eq "Win32" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "bin\plugins\NotepadStarterPlugin.dll" -FileName NotepadStarterPlugin.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v141_xp") {
            if($env:PLATFORM_INPUT -eq "x64"){
              $ZipFileName = "NotepadStarter_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
              7z a $ZipFileName bin\$env:PLATFORM_INPUT\$env:CONFIGURATION\NotepadStarterPlugin.dll
            }
            if($env:PLATFORM_INPUT -eq "Win32"){
              $ZipFileName = "NotepadStarter_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
              7z a $ZipFileName bin\plugins\NotepadStarterPlugin.dll
            }
        }

artifacts:
  - path: NotepadStarter_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: !!TODO, see https://www.appveyor.com/docs/deployment/github/#provider-settings!!
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v141_xp
        configuration: Release
